Feature/ugc service api
Pummas/ugc_sprint_1 pull request #13
Opened 2023-02-09 14:15 UTC by RomanBorovskiy

Запуск пока локально, без контейнера

2023-02-09 16:45 UTC, s-morichev requested changes
Лишний файл ugc/__init__.py

2023-02-09 16:45 UTC, s-morichev commented on ugc/src/core/storage_service.py
> +class StorageService(ABC):
В чем смысл использования StorageService? Насколько я понял, он обеспечивает синглтон для сервиса в 
 deps.py  storage: FilmViewStorage = StorageService.get_storage(StorageType.FILM_VIEW), но можно, например, создать экземпляр класса в некотором модуле и просто ссылаться на него

2023-02-09 16:45 UTC, s-morichev commented on ugc/src/core/storage_service.py
> +    MOCK = 0
Кажется MOCK = 0 нигде не используется, тогда надо удалить

2023-02-09 16:45 UTC, s-morichev commented on ugc/src/core/auth_bearer.py
> +        # todo check token
Что тут проверить надо?

2023-02-09 19:11 UTC, RomanBorovskiy commented on ugc/src/core/storage_service.py
> +class StorageService(ABC):
StorageService - интерфейс по сути. А потомки знают куда и как сохранять данные в зависимости от типа этих данных. В другой топик или в другую базу. Или в память

2023-02-09 19:15 UTC, RomanBorovskiy commented on ugc/src/core/storage_service.py
> +    MOCK = 0
зарезервировал значение для MOCK. Сначала тесты через него делал, а потом решил что покрытие слишком маленькое и мокнул кафку, точнее метод для сохранения. Можно удалить, но если вдруг потребуется в тестах делать мок-потомка - лучше оставить.

2023-02-09 19:18 UTC, RomanBorovskiy commented on ugc/src/core/auth_bearer.py
> +        # todo check token
Думал проверить токен на соответствие полей. Такой вариант - у нас появился auth v2, который выдает новые токены, где-то остались старые токены, которые по полям не подходят. Но наверное проще при этом будет поменять secret-key и все токены сделать не валидными... Наверное и нет смысла....

2023-02-10 15:54 UTC, s-morichev approved these changes

2023-02-11 07:23 UTC, s-morichev requested changes
Не нужно указывать версию в docker-compose.yml, параметр version DEPRECATED https://docs.docker.com/compose/compose-file/#compose-file

2023-02-11 07:23 UTC, s-morichev commented on ugc/docker/entrypoint.sh
> +echo "Waiting for Kafka"
Вывод Waiting for Kafka дублируется в wait_for_services.py, надо убрать здесь или там

2023-02-11 16:54 UTC, RomanBorovskiy commented on ugc/docker/entrypoint.sh
> +echo "Waiting for Kafka"
Заменил на "Waiting for required services..."

2023-02-11 16:59 UTC, s-morichev approved these changes

2023-02-12 14:36 UTC, Pummas approved these changes

2023-02-12 17:12 UTC, merged