Feature/sentry
Pummas/ugc_sprint_1 pull request #27
Opened 2023-02-20 10:23 UTC by s-morichev

2023-02-28 11:48 UTC, RomanBorovskiy requested changes

2023-02-28 11:48 UTC, RomanBorovskiy commented on etl/src/config.py
> +    SENTRY_PROJECT: str = Field("yp-ugc-service", env="SENTRY_PROJECT")
Не нашел где применяются эти параметры. Они нужны?

2023-02-28 11:48 UTC, RomanBorovskiy commented on ugc/src/db/kafka_producer.py
> +        sentry_sdk.capture_exception(err)
sentry по умолчанию логирует logging.error. Есть ли смысл дублировать сообщения?

2023-02-28 13:40 UTC, s-morichev commented on etl/src/config.py
> +    SENTRY_PROJECT: str = Field("yp-ugc-service", env="SENTRY_PROJECT")
В коде не используются, надо удалить.Но сами переменные окружения нужны, Senrty использует их для работы

2023-02-28 13:45 UTC, s-morichev commented on ugc/src/db/kafka_producer.py
> +        sentry_sdk.capture_exception(err)
В capture_exceptions захватывается дополнительная информация, тут скорее нужно настроить sentry, чтобы logging.error не приводило к отправке события.

2023-02-28 16:46 UTC, valerycode approved these changes
Хорошая работа!

2023-02-28 16:46 UTC, valerycode commented on etl/requirements.txt
> +orjson==3.8.5
nit: уже есть более новые версии orjson и sentry-sdk

2023-02-28 16:46 UTC, valerycode commented on etl/src/sentry.py
> +    if settings.ENABLE_SENTRY:
Классно, что есть проверка на включение/отключение sentry перед ее инициализацией. Позволит избежать возможного падания сервиса при запуске.

2023-02-28 16:46 UTC, valerycode commented on ugc/src/db/kafka_producer.py
> +        sentry_sdk.capture_exception(err)
nit: В коде из модуля sentry_sdk используется только функция capture_exception. Можно было бы только ее импортировать.

2023-03-01 09:49 UTC, RomanBorovskiy approved these changes

2023-03-01 12:07 UTC, merged