add user info db (Mongodb) and routes
Pummas/ugc_sprint_1 pull request #32
Opened 2023-02-27 11:33 UTC by Pummas

2023-02-28 08:42 UTC, s-morichev requested changes
1. Для моделей уже есть отдельный модуль src/models, логичнее перенести модели для монги в ту папку и унаследовать их от core.core_model.CoreModel
2. Не предусмотрены структуры данных для получения количества лайков у фильма, списка понравившихся фильмов у юзера. Текущая реализаця потребует фулл-скан всей базы
3. Желательно при старте приложения, например в `@app.on_event("startup")` добавить проверку c бэкоффом что монга стартовала
4. Нужно учесть, что монга может быть недоступна. Сейчас в этом случае приложение падает с pymongo.errors.ServerSelectionTimeoutError

2023-02-28 08:42 UTC, s-morichev commented on docker-compose.yml
> +      MONGO_INITDB_ROOT_PASSWORD: user_password
Перенести чувстительную информацию в env файл, добавить пример в env,example

2023-02-28 08:42 UTC, s-morichev commented on ugc/src/db/user_info_db/models.py
> +        super().__init__(**data)
Метод init не нужен, так как он делает то же самое, что и default_factory

2023-02-28 08:42 UTC, s-morichev commented on ugc/src/core/config.py
> +                           env="UGC_MONGO_URL")
Добавить пример UGC_MONGO_URL в env.example

2023-02-28 19:27 UTC, RomanBorovskiy requested changes
Предполагаю ручки должны еще позволять удалять значения и редактировать уже внесенные. Редактирование можно предусмотреть в тех же ручках - проверять на существующие значения и перезаписывать их при необходимости.

2023-02-28 19:27 UTC, RomanBorovskiy commented on ugc/src/db/user_info_db/database.py
> +db = client["prod-db"]
желательно вынести в конфиг. Не обязательно из переменной окружения брать, это позже можно добавить

2023-02-28 19:27 UTC, RomanBorovskiy commented on ugc/src/api/v1/user_info.py
> +async def add_like(film_id: str,
Должны быть лайки и дизлайки - их надо различать. В теории предлагают ставить оценку, 0 - дизлайк, 10 - лайк.

2023-02-28 19:27 UTC, RomanBorovskiy commented on ugc/src/api/v1/user_info.py
> +    save_response = await db["reviews"].insert_one(model)
Здесь, как и в других ручках нет проверки на повтор. То есть можно бесконечно добавлять значения, и они добавятся, так как _id будет новый. Правильнее будет проверять на существование записи, если она есть - менять ее

2023-03-01 08:18 UTC, Pummas commented on docker-compose.yml
> +      MONGO_INITDB_ROOT_PASSWORD: user_password
Оставил специально, должна появиться база из исследования
Комментарии 1-4 поправил

2023-03-01 08:19 UTC, Pummas commented on ugc/src/db/user_info_db/models.py
> +        super().__init__(**data)
Убрал, спасибо, забыл про него

2023-03-01 08:19 UTC, Pummas commented on ugc/src/core/config.py
> +                           env="UGC_MONGO_URL")
Пока нет необходимости, пусть пока берет дефолт

2023-03-01 08:19 UTC, Pummas commented on ugc/src/db/user_info_db/database.py
> +db = client["prod-db"]
prod-db вынес

2023-03-01 08:19 UTC, Pummas commented on ugc/src/api/v1/user_info.py
> +async def add_like(film_id: str,
Сделано

2023-03-01 12:11 UTC, valerycode approved these changes
OK

2023-03-01 12:56 UTC, s-morichev requested changes

2023-03-01 12:56 UTC, s-morichev commented on ugc/src/api/v1/bookmarks.py
> +@router.get("/{bookmark_id}", response_model=List[Bookmark])
bookmark_id в пути не нужно, тут получение всех закладок, а не одной.

2023-03-01 12:56 UTC, s-morichev commented on ugc/src/api/v1/likes.py
> +from pymongo.errors import ServerSelectionTimeoutError
Неиспользуемый импорт

2023-03-01 12:56 UTC, s-morichev commented on ugc/src/api/v1/likes.py
> +        raise HTTPException(status_code=400, detail="Рейтинг должен быть 0 или 10")
В add_like такой проверки нет. Наверное, она должна быть и там и там, либо убрать ее

2023-03-01 14:07 UTC, Pummas commented on ugc/src/api/v1/likes.py
> +        raise HTTPException(status_code=400, detail="Рейтинг должен быть 0 или 10")
Есть в pydantic модели эта проверка

2023-03-01 16:03 UTC, RomanBorovskiy commented on ugc/src/core/config.py
> +                           env="UGC_MONGO_URL")
Есть необходимость) В контейнере в докере не localhost:27017 должен быть, а mongodb_container:27017

2023-03-01 16:24 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
> +    except Exception as e:
не любят на ревью такие перехваты) Надо конкретный эксепшен ловить

2023-03-01 16:31 UTC, s-morichev approved these changes

2023-03-01 17:01 UTC, merged

2023-03-01 17:38 UTC, RomanBorovskiy requested changes

2023-03-01 17:38 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
> +        return {"success": True, "id": str(result.inserted_id)}
Если response_model=Bookmark, то такой return вывалится с ошибкой

2023-03-01 17:38 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
> +@router.post("/", response_model=Bookmark)
дело вкуса, но не проще ли film_id включить в путь ( /bookmarks/{film_id})? Сейчас вызов будет такой: /bookmarks/?film_id=FILM_ID

2023-03-01 17:38 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
> +    if await collection.find_one({"film_id": film_id, "user_id": user_id}):
Надо отслеживать исключения если база будет недоступна

2023-03-01 17:38 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
> +        return {"success": False, "error": str(e)}
Происходит ошибка, но при этом http_status_code == 200. Допустимо, если такая схема принята. Но везде до этого придерживались, что при ошибке ответ 4хх

2023-03-01 17:38 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
> +        raise HTTPException(status_code=400, detail=f"Bookmark already exist")
На ревью будет замечание - не использовать числовые значения, заменить на HTTPStatus.Ok