Feature/user info
Pummas/ugc_sprint_1 pull request #39
Opened 2023-03-01 21:09 UTC by Pummas

2023-03-01 22:37 UTC, RomanBorovskiy requested changes

2023-03-01 22:37 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
>      if await collection.find_one({"film_id": film_id, "user_id": user_id}):
общее - надо перехватывать исключения при обращении к базе. Думаю можно оставить до ревью

2023-03-01 22:37 UTC, RomanBorovskiy commented on ugc/src/api/v1/bookmarks.py
>          return {"success": False, "error": str(e)}
Происходит ошибка, а возвращается код 200. Хотя везде придерживались схемы при ошибке 4хх возвращать.

2023-03-01 22:37 UTC, RomanBorovskiy commented on ugc/src/api/v1/likes.py
>      dislikes = await collection.count_documents({"film_id": film_id, "rating": 10})
наоборот: лайк это много=10, дизлайк мало=0.

2023-03-01 22:37 UTC, RomanBorovskiy commented on ugc/src/api/v1/reviews.py
> +    text: str,
наверное правильнее текст обзора передавать в теле запроса, а не через путь

2023-03-01 22:37 UTC, RomanBorovskiy commented on ugc/src/api/v1/reviews.py
>  @router.get("/", response_model=List[Review])
больше придирка - для чего может потребоваться список всех обзоров на все фильмы всех пользователей? либо обзоры на фильм, либо все обзоры пользователя,  либо обзор на фильм только этого пользователя. Иначе там список может быть оооочень большой

2023-03-02 08:42 UTC, Pummas commented on ugc/src/api/v1/reviews.py
>  @router.get("/", response_model=List[Review])
Написано было при гибкую возможность поиска) Можно искать как угодно)

2023-03-02 08:43 UTC, Pummas commented on ugc/src/api/v1/reviews.py
> +    text: str,
В идеале сделать pydantic модель по которой передавать)

2023-03-02 08:43 UTC, Pummas commented on ugc/src/api/v1/likes.py
>      dislikes = await collection.count_documents({"film_id": film_id, "rating": 10})
Поменял

2023-03-02 08:43 UTC, Pummas commented on ugc/src/api/v1/bookmarks.py
>          return {"success": False, "error": str(e)}
Да, точно

2023-03-02 08:43 UTC, Pummas commented on ugc/src/api/v1/bookmarks.py
>      if await collection.find_one({"film_id": film_id, "user_id": user_id}):
Перехвачу

2023-03-02 12:40 UTC, RomanBorovskiy approved these changes

2023-03-02 12:46 UTC, valerycode approved these changes

2023-03-02 12:48 UTC, merged