Add research for Clickhouse
Pummas/ugc_sprint_1 pull request #7
Opened 2023-02-06 12:28 UTC by valerycode

Add research for Clickhouse

2023-02-06 12:55 UTC, Pummas approved these changes

2023-02-06 14:29 UTC, RomanBorovskiy requested changes

2023-02-06 14:29 UTC, RomanBorovskiy commented on research/clickhouse/load_data.py
> +MOVIES_NUMBER = 10000
Не используются константы, наверное нет в них смысла?

2023-02-06 14:29 UTC, RomanBorovskiy commented on research/clickhouse/load_data.py
> +                "movie_id": str(uuid4()),
Спорная генерация, весьма вероятно все user_id и все movie_id будут уникальными во всей базе и агрегации просто не получится... Лучше сгенерировать списки пользователей и фильмов и из них уже вытаскивать случайные

2023-02-06 15:30 UTC, s-morichev commented on research/clickhouse/tests.py
> +            "movie_id": "faa8f831-264d-4326-8517-12cdf5fd249e",
Получается, эти id встречаются в базе только один раз. Хорошо бы заранее сделать списки id, включить в них эти тестовые id и вставлять с базу значения из этих списков. По-моему, так будет реалистичнее.

2023-02-11 18:36 UTC, valerycode commented on research/clickhouse/load_data.py
> +MOVIES_NUMBER = 10000
Поправила

2023-02-11 18:36 UTC, valerycode commented on research/clickhouse/load_data.py
> +                "movie_id": str(uuid4()),
Сделала

2023-02-11 20:31 UTC, RomanBorovskiy commented on research/clickhouse/load_data.py
> +                "id": random.randint(0, 100000),
NIT: можно было бы вместо случайного числа брать i*BATCH_SIZE + j, где j - второй итератор. Тогда бы все id были уникальными

2023-02-11 20:32 UTC, RomanBorovskiy commented on research/clickhouse/load_data.py
> +            client.execute(QUERY, values)
NIT: Если бы здесь еще счетчик шел - было бы замечательно чтобы понять сколько еще осталось)

2023-02-11 20:43 UTC, RomanBorovskiy commented on research/clickhouse/select_tests.py
> +            for _ in range(ITERATIONS):
NIT: для таких вот счетчиков есть библиотека tqdm.  
`for _ in tqdm(range(ITERATIONS), postfix=query):`
И все выглядит замечательно

2023-02-11 20:48 UTC, RomanBorovskiy commented on research/clickhouse/select_tests.py
> +            avg = calculate_avg(results)
NIT: для этого есть statistics.mean()

2023-02-12 00:12 UTC, RomanBorovskiy commented on research/clickhouse/select_test_results.txt
> +Query_name: select_movies_by_user, Average_exec_time: 0.11394890069961548
тестов 5, а значений только 4...

2023-02-12 00:13 UTC, RomanBorovskiy approved these changes

2023-02-12 09:10 UTC, s-morichev approved these changes
Несколько улучшений для удобства использования (возможно излишних для одноразовой задачи)
1. Добавить скрипт для запуска всех тестов одной командой, main.py например
2. Добавить прогресс выполнения, tqdm или простые принты

2023-02-12 14:37 UTC, Pummas approved these changes

2023-02-12 16:54 UTC, merged